### ISSUE TITLE
Wrong orioledb patchset version: expected 23, got 1

### ISSUE THREAD

**Issue by 0xgeert** [orioledb/orioledb#359]
Excuse the issue here, not sure where to post otherwise. 

Im trying to install OrioleDB from source and getting: 

```
Wrong orioledb patchset version: expected 23, got 1
Rebuild and install patched orioledb/postgres using tag 'patches16_23'
make: *** [Makefile:264: check_patchset_version] Error 1

```

However, I've now triple-checked I've correctly installed the patched postgres version as stated. I've both tried: 

1) git clone 'orioledb/postgres' + 'git branch patches16_23'
2) download a zip of patches16_23. 

However still getting above error. What could be wrong?

**Comment by homper** [comment]
Sorry, just checked and yes, we need to clarify this in documentation
I mostly installing using method described in https://github.com/orioledb/orioledb/tree/main/doc/dev_quickstart.md:
```sh
git clone https://github.com/orioledb/postgres.git --branch patches16 --single-branch
cd postgres
git checkout patches16_23 # or you can reset to this tag on any branch, but commit with tag should be used
# configure, build
```
or even single commit by tag
```sh
git clone https://github.com/orioledb/postgres.git --branch patches16_23 --depth=1
cd postgres
# configure, build
```
ORIOLEDB_PATCHSET_VERSION determined using git tag name so it works this way

About your approaches:
1. `git branch patches16_23` is not working because it just creates new branch from default one which is still patches14. We, probably, need to change default branch in postgres repository, because we stoped supporting postgres 14 already.
2. extracting zip of patches16_23 not working because we overlooked that you need to add ORIOLEDB_PATCHSET_VERSION to postgres so our Makefile can determine version.

Running this inside the extracted postgres directory should fix the issue:
```sh
echo "ORIOLEDB_PATCHSET_VERSION = `echo patches16_23 | cut -d'_' -f2`" >> src/Makefile.global
```
