### ISSUE TITLE
Cannot build project, missing ExecInitFuncHook

### ISSUE THREAD

**Issue by bjanjic** [orioledb/orioledb#39]
In postgres patch project ExecInitFuncHook was recently removed:
https://github.com/orioledb/postgres/commit/6b7284090e0c12b5829bdd4d11b8b8eac08b92a9

However in orioledb.c (line 591) it is still used so project cannot be built.

**Comment by homper** [comment]
Sorry about that, my fault
Now should work

**Comment by akorotkov** [comment]
@homper, I don't think you did wrong.
@homper, the issue is that now readme references specific tags on orioledb/postgres.  So, you should build with https://github.com/orioledb/postgres/commit/5e283ccb14cd1e42b2e289741be3cc9a4d7f600e.
The branches on orioledb/postgres may refrect development state of patches.  You shouldn't use them for build.

**Comment by bjanjic** [comment]
Thanks @akorotkov I think we can close this ticket now.
